In [1]:
import numpy as np

In [2]:
my_list=[-1,0,1]

In [3]:
my_list,type(my_list)

([-1, 0, 1], list)

In [4]:
my_array=np.array(my_list)

In [5]:
my_array,type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
  np.arange(0,11,2,dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [8]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [9]:
np.linspace(1,15,15,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]), 1.0)

In [10]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
arr_1=np.arange(1,11)

In [15]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_1.shape=(2,5)

In [18]:
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])